name: Deploy Complex
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t vetrax/multi-client ./client
      - run: docker build -t vetrax/multi-nginx ./nginx
      - run: docker build -t vetrax/multi-server ./server
      - run: docker build -t vetrax/multi-worker ./worker
